### ISSUE TITLE
Error exception carballo-uci-1.7

### ISSUE THREAD

**Issue by aprijal-psrb** [albertoruibal/carballo#4]
Here my command:

D:\CE\carballo-uci-1.7>carballo.bat
D:\CE\carballo-uci-1.7>java -jar carballo-1.7.jar -Xmx1024M
Carballo Chess Engine v1.7 by Alberto Alonso Ruibal
uci
id name Carballo Chess Engine v1.7
id author Alberto Alonso Ruibal
option name Hash type spin default 64 min 16 max 1024
option name Ponder type check default true
option name OwnBook type check default true
option name UCI_Chess960 type check default false
option name Evaluator type combo default complete var simplified var complete var experimental
option name Contempt Factor type spin default 90 min -200 max 200
option name Elo type spin default 2100 min 500 max 2100
uciok
go movetime 1000
Exception in thread "main" java.lang.NullPointerException
        at com.alonsoruibal.chess.uci.Uci.loop(Unknown Source)
        at com.alonsoruibal.chess.uci.Uci.main(Unknown Source)

**Comment by aprijal-psrb** [comment]
ohh i see. After i look Uci.java code, "engine" defined after isready command. Why not defined it at Uci constructor and make reloadEngine() function so that's function must be called after "setoption" command?.

**Comment by albertoruibal** [comment]
Hello! The engine is not initialized until the "isready" command because it needs to know the UCI parameters (like the hash table size) before the initialization.

In the UCI protocol specs at http://wbec-ridderkerk.nl/html/UCIProtocol.html says:
> * isready
> [...]
> 	This command is also required once before the engine is asked to do any search to wait for the engine to finish initializing.
> [...]

I will add an error message (better than the exception) to tell that "isready" must be sent before. 

Thank you!
