### ISSUE TITLE
Use java intrinsic methods

### ISSUE THREAD

**Issue by sandermvdb** [albertoruibal/carballo#6]
Hi,

I was wondering why you have implemented methods like popCount(), lsb(), msb() if you can use intrinsic versions of these methods: Long.bitCount(), Long.numberOfTrailingZeros(), etc...? The idea of these intrinsic methods is that the JVM swaps these methods with handwritten code that is optimized for a certain architecture.
A list of intrinsic methods:
http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509/src/share/vm/classfile/vmSymbols.hpp#l581

Btw, I've written a chessengine myself which maybe one day will be as good as carballo :)
https://github.com/sandermvdb/chess22k

Regards!
Sander

**Comment by albertoruibal** [comment]
Hello Sander!

This is because I didn't knew about the existence of these methods :)

I am changing the code to use the intrinsic methods, and at the moment I'm not noticing a performance increase in the x86_64 linux JVM, but it will reduce the code size.

Thank you! I will follow your progress with chess22k, sure it will be better than carballo!
